//import 'package:MovieWorld/constant/ImageConstant.dart';
//import 'package:MovieWorld/model/Movie.dart';
//
//const FAKE_DATA = const [
//  Movie(
//    id: "1",
//    name: "The Shack",
//    rate: 6.4,
//    imageUrl: ImageConstant.POSTER1,
//    status: "nowshowing",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "Một hàng giống như một cột nhưng xây dựng một hàng vật dụng nằm ngang thay vì một cột. Sự khác biệt chính ở đây là trục chính là trục ngang chứ không phải trục dọc. Trục chéo là trục dọc.",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//
//  Movie(
//    id: "2",
//    name: "Avenger",
//    rate: 7.5,
//    imageUrl: ImageConstant.POSTER2,
//    status: "nowshowing",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "3",
//    name: "Chiếc lá cuốn bay",
//    rate: 7.4,
//    imageUrl: ImageConstant.POSTER3,
//    status: "nowshowing",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "4",
//    name: "China",
//    rate: 5.0,
//    imageUrl: ImageConstant.POSTER4,
//    status: "comingsoon",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "5",
//    name: "Hai Phượng",
//    rate: 6.4,
//    imageUrl: ImageConstant.POSTER5,
//    status: "comingsoon",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "6",
//    name: "Iteawon Class",
//    rate: 6.4,
//    imageUrl: ImageConstant.POSTER6,
//    status: "comingsoon",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "6",
//    name: "Kingdom",
//    rate: 6.4,
//    imageUrl: ImageConstant.POSTER7,
//    status: "comingsoon",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "6",
//    name: "Mắt Biếc",
//    rate: 6.4,
//    imageUrl: ImageConstant.POSTER8,
//    status: "nowshowing",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//  Movie(
//    id: "6",
//    name: "Người phán xử",
//    rate: 6.4,
//    imageUrl: ImageConstant.POSTER9,
//    status: "nowshowing",
//    trailerUrl:"",
//    timeLimit : 120,
//    artist: "khgcias",
//    director: "kasgdiwugd",
//    content: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//    nation: "vietnam",
//    genre: "Action, Adventure",
//    premiere: "14.4.2020",
//  ),
//
//];